Tienda.AppWeb/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tienda.Logic;

namespace Tienda.AppWeb.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {
            var listado = ClienteBL.Listar();
            return View(listado);
        }
    }
}

Tienda.AppWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tienda.AppWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Tienda.AppWeb/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tienda.Logic;

namespace Tienda.AppWeb.Controllers
{
    public class ProductosController : Controller
    {
        // GET: Productos
        public ActionResult Index()
        {
            var listaProductos = ProductoBL.Listar();
            return View(listaProductos);
        }

        public ActionResult Editar(int id)
        {
            var producto = ProductoBL.ObtenerPorId(id);
            ViewBag.categorias = CategoriaBL.Listar();
            return View(producto);
        }
    }
}

Tienda.AppWeb/Views/Cliente/Index.cshtml
@model IEnumerable<Tienda.Core.Cliente>
@{
    ViewBag.Title = "Index";
}

<h2>Listado de Clientes</h2>
<table class="table table-hover">
    <thead>
        <tr>
            <th>N° Documento</th>
            <th>Nombre</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.NroDocumento</td>
                <td>@item.Nombre</td>
            </tr>
        }
    </tbody>    
</table>

Tienda.AppWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Tienda.AppWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Tienda.AppWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Tienda.AppWeb/Views/Productos/Editar.cshtml
@model Tienda.Core.Producto
@{
    ViewBag.Title = "Editar";
}

<h2>Editar Producto</h2>
@using (Html.BeginForm())
{

    <div class="form-group">
        @Html.LabelFor(model => Model.Nombre)
        @Html.TextBoxFor(model => Model.Nombre, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => Model.Marca)
        @Html.TextBoxFor(model => Model.Marca, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => Model.IdCategoria, "Categoría")
        @Html.DropDownListFor(model => Model.IdCategoria, new SelectList(ViewBag.categorias, "IdCategoria", "Nombre"), new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => Model.Precio)
        @Html.TextBoxFor(model => Model.Precio, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => Model.Stock)
        @Html.TextBoxFor(model => Model.Stock, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => Model.Observacion)
        @Html.TextAreaFor(model => Model.Observacion, new { @class = "form-control" })
    </div>
}

Tienda.AppWeb/Views/Productos/Index.cshtml
@model IEnumerable<Tienda.Core.Producto>
@{
    ViewBag.Title = "Index";
}

<h2>Nuestros Productos</h2>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">@item.Nombre</h3>
                </div>
                <div class="panel-body">
                    <p>@item.Observacion</p>
                </div>
                <div class="panel-footer">
                    @Html.ActionLink("Editar", "Editar", "Productos", new {id = item.IdProducto}, new {@class = "btn btn-primary"})
                </div>
            </div>
        </div>
    }
</div>

Tienda.AppWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Clientes", "Index", "Cliente")</li>
                    <li>@Html.ActionLink("Productos", "Index", "Productos")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>